### ISSUE TITLE
Valid AppID but requires registration.

### ISSUE THREAD

**Issue by ghost** [constituentvoice/YahooBoss-Python#1]
The BOSS API seems to be broken from Python. It returns:

'{"error":{"lang":"en-US","description":"Valid AppID but requires registration."}}'

**Comment by cfreak-dev** [comment]
Brian,

The message you're receiving is from Yahoo. It seems to be an issue several people have had on their forums. According to this post: https://developer.yahoo.com/forums/#/discussion/6407/yahoo-boss-search-limited-web-valid-appid-but-requires-registration  you likely need to contact Yahoo support.
